title: Nroskill's Blog
baseurl: ""
url: "https://nroskill.github.io/"
email: nroskill@gmail.com
twitter_username: nroskill
github_username:  nroskill
# 链接格式
permalink: /:title
# 插件
gems: [jekyll-paginate]
# markdown解析器
markdown: kramdown
# google analytics
google_analytics: UA-33809015-2

# 分页
# paginate: 2
# 代码高亮
# highlighter: pygments